import type { NextPage, GetStaticProps } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

interface HomeProps {
  posts: Post[]
}

const Home: NextPage<HomeProps> = (props) => {

  const { posts } = props
  console.log(posts)

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Izzy MG&lsquo;s writings
        </h1>

        <p className={styles.description}>
          Here&lsquo;s where I work with Next.JS and sometimes write stuff. Check out my <a href="http://izzymg.dev">portfolio</a>!
        </p>

      </main>
    </div>
  )
}

export const getStaticProps: GetStaticProps = async ctx => {

  const posts: Post[] = [
    {
      title: "Hello, here's a fake post",
      slug: "post-a",
      date: new Date(Date.now()).toDateString()
    },
    {
      title: "Another fake post.",
      slug: "post-b",
      date: new Date(Date.now()).toDateString()
    },
  ]

  return {
    props: { posts }, 
  }
}

export default Home
